apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: bluegreen
    version: {{ .Values.activeColor }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
