name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPO_NAME: blue_green_deploymemnt
  IMAGE_TAG: latest
  CLUSTER_NAME: blue_green_deploymt-cluster
  RELEASE_NAME: bluegreen
  HELM_CHART_PATH: ./helm

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Print checkout status
        run: echo "Source code checked out successfully"

      - name: Build Docker image
        run: |
          echo "Building Docker image"
          docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
          echo "Docker image built successfully"

      - name: Save Docker image as artifact
        run: |
          echo "Saving Docker image as artifact"
          docker save $ECR_REPO_NAME:$IMAGE_TAG | gzip > image.tar.gz

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar.gz

  push:
    name: Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: |
          echo "Loading Docker image"
          gunzip -c image.tar.gz | docker load

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image for ECR
        run: |
          echo "Tagging Docker image"
          docker tag $ECR_REPO_NAME:$IMAGE_TAG \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          echo "Pushing Docker image to ECR"
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
          echo "Docker image pushed to ECR successfully"

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name $CLUSTER_NAME \
            --region $AWS_REGION

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy using Helm (Blueâ€“Green)
        run: |
          echo "Deploying application using Helm"
          helm upgrade --install $RELEASE_NAME $HELM_CHART_PATH \
            --set image.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO \
            --set image.tag=latest \
            --set activeColor=green
