name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      ECR_REPO_NAME: bluegreen-python-app
      IMAGE_TAG: latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Print checkout status
        run: echo "ðŸ“¥ Source code checked out successfully"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Print ECR login status
        run: echo "Logged in to Amazon ECR successfully"

      - name: Build Docker image
        run: |
          echo "Building Docker image"
          docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
          echo "Docker image built successfully"

      - name: Tag Docker image for ECR
        run: |
          echo "Tagging Docker image"
          docker tag $ECR_REPO_NAME:$IMAGE_TAG \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          echo "Pushing Docker image to ECR"
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
          echo "Docker image pushed to ECR successfully"